"""add garden area and water pool

Revision ID: 037cd3a92706
Revises: e999c5ec8411
Create Date: 2026-05-28 16:38:59.941953

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '037cd3a92706'
down_revision = 'e999c5ec8411'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('gardens', sa.Column('garden_area', sa.Integer(), nullable=False))
    op.add_column('gardens', sa.Column('has_water_pool', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('gardens', 'has_water_pool')
    op.drop_column('gardens', 'garden_area')
    # ### end Alembic commands ###
