"""fix garden id autoincrement

Revision ID: 2487c2513b69
Revises: 9d39ea303408
Create Date: 2026-06-02 16:30:01.316708

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2487c2513b69'
down_revision = '9d39ea303408'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
