"""many to many plants and tools

Revision ID: 4d763c5991ff
Revises: 037cd3a92706
Create Date: 2026-05-28 18:01:38.520475

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4d763c5991ff'
down_revision = '037cd3a92706'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('garden_plants',
    sa.Column('garden_id', sa.Integer(), nullable=False),
    sa.Column('plant_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['garden_id'], ['gardens.id'], ),
    sa.ForeignKeyConstraint(['plant_id'], ['plants.id'], ),
    sa.PrimaryKeyConstraint('garden_id', 'plant_id')
    )
    op.create_table('garden_tools',
    sa.Column('garden_id', sa.Integer(), nullable=False),
    sa.Column('tool_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['garden_id'], ['gardens.id'], ),
    sa.ForeignKeyConstraint(['tool_id'], ['tools.id'], ),
    sa.PrimaryKeyConstraint('garden_id', 'tool_id')
    )
    op.drop_constraint('plants_garden_id_fkey', 'plants', type_='foreignkey')
    op.drop_column('plants', 'garden_id')
    op.drop_constraint('tools_garden_id_fkey', 'tools', type_='foreignkey')
    op.drop_column('tools', 'garden_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tools', sa.Column('garden_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.create_foreign_key('tools_garden_id_fkey', 'tools', 'gardens', ['garden_id'], ['id'])
    op.add_column('plants', sa.Column('garden_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.create_foreign_key('plants_garden_id_fkey', 'plants', 'gardens', ['garden_id'], ['id'])
    op.drop_table('garden_tools')
    op.drop_table('garden_plants')
    # ### end Alembic commands ###
