"""many to many plants and tools

Revision ID: 9d39ea303408
Revises: 4d763c5991ff
Create Date: 2026-05-29 13:04:10.112579

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9d39ea303408'
down_revision = '4d763c5991ff'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
